---
apiVersion: v1
kind: Namespace
metadata:
  name: chronograf
---
apiVersion: v1
kind: Service
metadata:
  name: chronograf-chronograf
  namespace: chronograf
  labels:
    app: chronograf-chronograf
    chart: "chronograf-1.2.6"
    release: "chronograf"
    heritage: "Helm"
    helm.sh/chart: chronograf-1.2.6
    app.kubernetes.io/name: chronograf
    app.kubernetes.io/instance: chronograf
    app.kubernetes.io/version: "1.9.4"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    app: chronograf-chronograf
    app.kubernetes.io/name: chronograf
    app.kubernetes.io/instance: chronograf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf-chronograf
  namespace: chronograf
  labels:
    app: chronograf-chronograf
    chart: "chronograf-1.2.6"
    release: "chronograf"
    heritage: "Helm"
    helm.sh/chart: chronograf-1.2.6
    app.kubernetes.io/name: chronograf
    app.kubernetes.io/instance: chronograf
    app.kubernetes.io/version: "1.9.4"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: chronograf-chronograf
      app.kubernetes.io/name: chronograf
      app.kubernetes.io/instance: chronograf
  template:
    metadata:
      labels:
        app: chronograf-chronograf
        app.kubernetes.io/name: chronograf
        app.kubernetes.io/instance: chronograf
    spec:
      containers:
      - name: chronograf
        image: "chronograf:1.11.1-alpine"
        imagePullPolicy: IfNotPresent
        env:
        - name: "HOST_PAGE_DISABLED"
          value: "false"
        - name: "INFLUXDB_URL"
          value: "http://influxdb-enterprise-data.influxdb-enterprise.svc.cluster.local:8086"
        - name: "INFLUXDB_USERNAME"
          value: "admin"
        - name: "INFLUXDB_PASSWORD"
          value: "changeme"
        - name: "INFLUXDB_INSECURE_SKIP_VERIFY"
          value: "true"
        ports:
        - containerPort: 8888
          hostPort: 8888
          name: api
        livenessProbe:
          httpGet:
            path: /ping
            port: api
        readinessProbe:
          httpGet:
            path: /ping
            port: api
        startupProbe:
          httpGet:
            path: /ping
            port: api
          initialDelaySeconds: 5
        volumeMounts:
        - name: data
          mountPath: /var/lib/chronograf
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 2
      volumes:
      - name: data
        emptyDir: {}
